local ReplicatedStorage = game:GetService("ReplicatedStorage")

local flagsFolder = ReplicatedStorage._Assets.Flags

local Flags: { Model } = {
	flagsFolder.Red,
	flagsFolder.Ace,
	flagsFolder.Aro,
	flagsFolder.Bi,
	flagsFolder.Checkers,
	flagsFolder.Enby,
	flagsFolder.Gay,
	flagsFolder.Italy,
	flagsFolder.Lesbian,
	flagsFolder.Noob,
	flagsFolder.Pan,
	flagsFolder.Pride,
	flagsFolder.Short,
	flagsFolder.Tall,
	flagsFolder.Trans,
	flagsFolder.Wedge,
	flagsFolder.Fluid,
	-- new ones start here
	flagsFolder.Curvy,
	flagsFolder.Flipped,
	flagsFolder.Stick,
	flagsFolder.Different,
	flagsFolder["Non-Linear"],
	flagsFolder.Lamp,
	flagsFolder.Evil,
	flagsFolder.Classic,
	flagsFolder.Expensive,
	flagsFolder.Green,
	flagsFolder.Source,
	flagsFolder.ERROR,
	flagsFolder.statue,
	flagsFolder.Brittle,
	flagsFolder.Burger,
	flagsFolder.Nothing,
	flagsFolder.Baby,
	flagsFolder["Too Tall"],
	flagsFolder["Burger With Lettuce"],
	flagsFolder.Aroace,
	flagsFolder.Bob,
}

return Flags
