return {
	announcementsEnabled = true,
	explosionsEnabled = true,
	sparklesEnabled = true,
	
	skybox = 1,
	
	chordingEnabled = false,
	ignoreFlags = true,

	highlightEnabled = true,
	highlightColor = Color3.new(1, 1, 1),
	highlightSpeed = 10,

	fieldColorLight = Color3.fromRGB(99, 95, 98),
	fieldColorDark = Color3.fromRGB(80, 77, 79),

	groundColorLight = Color3.fromRGB(248, 248, 248),
	groundColorDark = Color3.fromRGB(200, 200, 200),

	fieldMaterial = 0,
	groundMaterial = 0,

	cameraShake = 0,
	topdownView = false,
	freezeCameraOnDeath = true,

	vignetteEnabled = true,

	characterVolume = 100,
	explosionVolume = 100,
	flagVolume = 100,
	alertVolume = 100,

	showTileCount = true,
	showMineCount = true,
	showFlagCount = true,
		
	showCoords = true,
	showRoundTimer = true,
	showSessionTimer = true,
	
	showScore = true,
}
